-- Seed Landing Page Content
-- This populates the landing_sections table with the current MentorEU landing page content

INSERT INTO landing_sections (section_key, section_type, title, subtitle, content, image_url, button_text, button_link, icon, order_number, is_active) VALUES

-- Hero Section
('hero_main', 'hero', 
  'Avrupa''da Eğitim Hayalinizi Gerçeğe Dönüştürün',
  'Almanya, İtalya, Hollanda ve daha fazlası... MentorEU ile Avrupa''nın en prestijli üniversitelerinde eğitim almanız artık çok kolay!',
  null,
  'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1920',
  'Ücretsiz Danışmanlık Alın',
  '#contact',
  null,
  1,
  true),

-- Features Section
('feature_personalized', 'feature',
  'Kişiselleştirilmiş Danışmanlık',
  null,
  'Hedeflerinize ve profilinize özel hazırlanmış eğitim planı. Her öğrenci için benzersiz bir yol haritası oluşturuyoruz.',
  null,
  null,
  null,
  'Target',
  1,
  true),

('feature_university', 'feature',
  'Üniversite Seçimi',
  null,
  'Avrupa''nın en iyi üniversiteleri arasından size en uygun olanı bulmanıza yardımcı oluyoruz. Doğru tercihi birlikte yapıyoruz.',
  null,
  null,
  null,
  'GraduationCap',
  2,
  true),

('feature_application', 'feature',
  'Başvuru Süreci',
  null,
  'Motivasyon mektubundan vize başvurusuna kadar tüm süreçte profesyonel destek. Her adımda yanınızdayız.',
  null,
  null,
  null,
  'FileText',
  3,
  true),

('feature_scholarship', 'feature',
  'Burs İmkanları',
  null,
  'Size uygun burs programlarını araştırıyor ve başvuru sürecinde rehberlik ediyoruz. Ekonomik çözümler sunuyoruz.',
  null,
  null,
  null,
  'Award',
  4,
  true),

('feature_visa', 'feature',
  'Vize Desteği',
  null,
  'Vize başvuru sürecinde A''dan Z''ye destek. Tüm evrakları eksiksiz hazırlayıp başarılı sonuç almanızı sağlıyoruz.',
  null,
  null,
  null,
  'Plane',
  5,
  true),

('feature_accommodation', 'feature',
  'Konaklama Yardımı',
  null,
  'Varış öncesi ve sonrası konaklama çözümleri. Güvenli ve uygun fiyatlı barınma seçenekleri sunuyoruz.',
  null,
  null,
  null,
  'Home',
  6,
  true),

('feature_support', 'feature',
  '7/24 Destek',
  null,
  'Avrupa''ya vardıktan sonra da yanınızdayız. Sürekli iletişim ve destek ile adaptasyon sürecinizi kolaylaştırıyoruz.',
  null,
  null,
  null,
  'MessageCircle',
  7,
  true),

-- How It Works Section
('how_it_works_step1', 'how_it_works',
  'İlk Görüşme',
  null,
  'Ücretsiz ön değerlendirme görüşmesinde hedeflerinizi, eğitim durumunuzu ve bütçenizi değerlendiriyoruz. Size özel bir yol haritası çizmeye başlıyoruz.',
  null,
  null,
  null,
  'UserPlus',
  1,
  true),

('how_it_works_step2', 'how_it_works',
  'Program Seçimi',
  null,
  'Uzman ekibimiz, profilinize uygun üniversiteleri ve programları araştırıyor. Size en uygun seçenekleri sunuyoruz ve birlikte karar veriyoruz.',
  null,
  null,
  null,
  'Search',
  2,
  true),

('how_it_works_step3', 'how_it_works',
  'Başvuru',
  null,
  'Tüm başvuru belgelerinizi profesyonelce hazırlıyoruz. Motivasyon mektubunuzdan referans mektuplarına kadar her şeyi titizlikle kontrol ediyoruz.',
  null,
  null,
  null,
  'Send',
  3,
  true),

('how_it_works_step4', 'how_it_works',
  'Kabul ve Vize',
  null,
  'Kabul mektubunuzu aldıktan sonra vize sürecinde size rehberlik ediyoruz. Tüm evrakları hazırlıyor ve başarılı vize başvurusu için destek oluyoruz.',
  null,
  null,
  null,
  'CheckCircle',
  4,
  true),

-- FAQ Section
('faq_who', 'faq',
  'MentorEU kimler için uygundur?',
  null,
  'MentorEU, Avrupa''da lisans, yüksek lisans veya doktora eğitimi almak isteyen tüm Türk öğrenciler için uygundur. Lise son sınıf öğrencilerinden mezunlara kadar herkese hizmet veriyoruz.',
  null,
  null,
  null,
  null,
  1,
  true),

('faq_cost', 'faq',
  'Danışmanlık ücreti nedir?',
  null,
  'İlk görüşme ve ön değerlendirme tamamen ücretsizdir. Detaylı paket fiyatlarımız, hizmet kapsamımıza göre değişiklik göstermektedir. Size özel teklif için bizimle iletişime geçin.',
  null,
  null,
  null,
  null,
  2,
  true),

('faq_duration', 'faq',
  'Süreç ne kadar sürer?',
  null,
  'Başvuru süreci ortalama 6-12 ay arasında değişmektedir. Bu süre, hedeflediğiniz program, ülke ve başlangıç tarihinize göre değişebilir. Erken başvuru her zaman avantajlıdır.',
  null,
  null,
  null,
  null,
  3,
  true),

('faq_scholarship', 'faq',
  'Burs almam garanti mi?',
  null,
  'Burs başvurularında garanti veremesek de, başarı oranınızı artırmak için elimizden geleni yapıyoruz. Size uygun tüm burs programlarını araştırıyor ve başvuru sürecinde profesyonel destek sağlıyoruz.',
  null,
  null,
  null,
  null,
  4,
  true),

('faq_after', 'faq',
  'Kabul aldıktan sonra da destek veriyor musunuz?',
  null,
  'Evet! Vize sürecinden konaklama ayarlamaya, havalimanı karşılamadan ilk haftalardaki adaptasyon sürecinize kadar size destek olmaya devam ediyoruz.',
  null,
  null,
  null,
  null,
  5,
  true),

('faq_countries', 'faq',
  'Hangi ülkelere başvuru yapabiliyorum?',
  null,
  'Almanya, İtalya, Hollanda, Fransa, İspanya, Belçika, Avusturya, İsveç gibi Avrupa ülkelerinin tümüne başvuru desteği sağlıyoruz. İhtiyacınıza göre birden fazla ülkeye başvuru yapabilirsiniz.',
  null,
  null,
  null,
  null,
  6,
  true),

-- Footer Contact Info
('footer_contact', 'footer',
  'İletişim Bilgileri',
  null,
  null,
  null,
  null,
  null,
  null,
  1,
  true),

('footer_about', 'footer',
  'MentorEU Hakkında',
  null,
  'Avrupa''da eğitim hayallerinizi gerçeğe dönüştürüyoruz. Profesyonel danışmanlık ile yanınızdayız.',
  null,
  null,
  null,
  null,
  2,
  true);

